name: task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  pinput: ^5.0.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  permission_handler: ^12.0.0+1
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  file_picker: ^10.3.3
  fluttertoast: ^9.0.0
  share_plus: ^12.0.0
  url_launcher: ^6.3.2
  loading_animation_widget: ^1.3.0
  carousel_slider: ^5.1.1
  equatable: ^2.0.5
  connectivity_plus: ^6.1.0
  percent_indicator: ^4.2.5
  dio: ^5.9.0
  image_cropper: ^11.0.0
  go_router: ^16.3.0

  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  flutter_launcher_icons: ^0.14.4
  pretty_dio_logger: ^1.3.1
  injectable_generator: ^2.12.0

flutter_gen:
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
  output: lib/gen/
  line_length: 100
  assets:
    outputs:
#  colors:
#    inputs:
#      - assets/color/colors.xml
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/color/
    - assets/icons/
    - assets/images/
#    - assets/logo/
#    - assets/json/
#    - assets/audio/
#    - .env

